### ISSUE TITLE
Fix on Windows

### ISSUE THREAD

**Issue by bubba** [bubba/lsp-test#28]
Currently lsp-test builds but doesn't really work on Windows. This should probably be fixed!

**Comment by fendor** [comment]
Found it.

**Comment by bubba** [comment]
@fendor Oh wow thanks for figuring this out! Either way I should start looking at fixing the threading situation, the fact that the server thread was dying and leaving the others to hang sounds like the cause of a lot of other hangs I've been seeing.

**Comment by bubba** [comment]
Closed in #39
