### ISSUE TITLE
Session should be a newtype

### ISSUE THREAD

**Issue by bubba** [bubba/lsp-test#34]
Without newtype its implementation ends up being exposed on haddock

**Comment by jacg** [comment]
... and also in compiler error messages ... which propagate into features provided by IDEs which consume those messages, all of which is a huge PITA.

Do you foresee any complications in doing this? I might be able to find the time to do it, if it's not going to be too complicated.

**Comment by bubba** [comment]
I have worked on this before, but there were some hurdles that I can't quite remember now. I've just pushed my changes to https://github.com/bubba/lsp-test/tree/session-newtype

**Comment by jacg** [comment]
Do I need to do anything to make the tests work via `stack test` beyond ensuring that `hie` is available? All tests fail (on master) with

       Couldn't decode response for the request type: Shutdown
       "{\"result\":\"ok\",\"jsonrpc\":\"2.0\",\"id\":0}"
       CallStack (from HasCallStack):
         error, called at src/Language/Haskell/LSP/Test/Decoding.hs:120:32 in lsp-test-0.7.0.0-CUarVrbXNnaBfF7ph1rHVW:Language.Haskell.LSP.Test.Decoding

 ... though, curiously, some pass if I replace `"hie"` with `"ghcide --lsp"` in the calls to `runSession` in test suite.

**Comment by bubba** [comment]
Try again with the current hie master! Hie was actually giving an incorrect shutdown response so the haskell-lsp-0.16 now (correctly) crashes when decoding it. Hie was just updated yesterday to use the new haskell-lsp with the correct shutdown response so they should match up now.
