### ISSUE TITLE
Test Suite fails for windows in "manual javascript session"

### ISSUE THREAD

**Issue by jneira** [bubba/lsp-test#43]
Hi, running the test suite fails for me with
```
manual javascript session
  passes a test FAILED [1]

Failures:

  test\Test.hs:137:5:
  1) manual javascript session passes a test
       uncaught exception: IOException of type NoSuchThing
       javascript-typescript-stdio: createProcess: does not exist (No such file or directory)
```
* I've installed `javascript-typescript-stdio` with `npm install -g javascript-typescript-langserver`
* I can run `javascript-typescript-stdio` in console, but in windows it is a `.cmd` script
* Adding `.cmd` in the test: `runSession "javascript-typescript-stdio.cmd" fullCaps "test/data/javascriptPass" $ ...` make it throw another error:

```
manual javascript session
  passes a test FAILED [1]

Failures:

  test\Test.hs:137:5:
  1) manual javascript session passes a test
       uncaught exception: SessionException
       Language server unexpectedly terminated
```

**Comment by bubba** [comment]
Hi, sorry for the really late reply. Does running the test with `runSessionWithConfig (defaultConfig { logStdErr = True, logMessages = True}) ...` give any more information?

**Comment by bubba** [comment]
The Javascript tests are gone in ddc2cdb9d0563dcf30102c8ef41dc6932717a872, they've been replaced with a dummy server instead
