### ISSUE TITLE
flush stack environment before running a test session

### ISSUE THREAD

**Issue by alanz** [bubba/lsp-test#57]
In order to fix various tests in hie to run with stack-2.1.3, I had to introduce `flushStackEnvironment` : https://github.com/alanz/haskell-ide-engine/blob/bfb16324d396da71000ef81d51acbebbdaa854ab/test/utils/TestUtils.hs#L290-L298.

It is also required to be called before `lsp-test` usage of `runSession`, as at https://github.com/alanz/haskell-ide-engine/blob/bfb16324d396da71000ef81d51acbebbdaa854ab/test/functional/FunctionalCodeActionsSpec.hs#L214-L218

So perhaps we should consider always calling that function inside `runSession`.

**Comment by bubba** [comment]
Could this be done with the `before_` hook in HSpec? https://hspec.github.io/writing-specs.html#using-hooks

**Comment by alanz** [comment]
Well, I was thinking more of helping other projects out. This is a consideration of using `lsp-test` with stack.

**Comment by cocreature** [comment]
Note that `lsp-test` is pretty agnostic to the LSP server, in particular you can use it for non-Haskell languages so I don’t think adding stack specific code there makes sense.

**Comment by alanz** [comment]
@cocreature I am also not sure if it belongs here. But to clarify, this is needed if you are using `lsp-test` in a project and that project is running tests using stack.  The latest stack sets various environment variables, and this can cause off breakage when you fork an `lsp-test` session, assuming you are running in a clean environment.

**Comment by bubba** [comment]
I think we can document this, either in the haddocks or the readme, as specific caveat to look out for if you are using lsp-test with a Haskell based language server

**Comment by alanz** [comment]
> lsp-test with a Haskell based language server

The use case is if you are writing a language server in haskell, using this library, and wanting to run tests on it.  What language the server being written supports is irrelevant.  It is about writing running tests that use `hieSession`, where the test itself is part of a stack project.
