### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by ndmitchell** [bubba/lsp-test#60]
Would it be possible to add this package into Stackage?

**Comment by bubba** [comment]
0.7.0.0 is already on Stackage nightly, but 0.8.2.0 is blocked by haskell-lsp, which is in turn blocked by hslogger it looks like

**Comment by ndmitchell** [comment]
Thanks for the info. I raised https://github.com/haskell-hvr/hslogger/issues/55 to ask hslogger to be put online.

**Comment by bubba** [comment]
Done in https://github.com/commercialhaskell/stackage/pull/5001#issuecomment-559680825
