### ISSUE TITLE
Problem decoding completion responses

### ISSUE THREAD

**Issue by astoff** [bubba/lsp-test#69]
Since updating from lsp-test 0.10 to 0.11, I get the following error in my tests:

       uncaught exception: ErrorCall
       Couldn't decode response for the request type: TextDocumentCompletion
       "{\"jsonrpc\":\"2.0\",\"result\":[{\"label\":\"raisebox\"}],\"id\":1}"
       CallStack (from HasCallStack):
         error, called at src/Language/Haskell/LSP/Test/Decoding.hs:120:32 in lsp-test-0.11.0.0-GD7z03pTFQZ9YYbBqXNnp9:Language.Haskell.LSP.Test.Decoding

Tests for other LSP methods still work, so it must really be something specific to how responses to completion requests are decoded. I also tried to make my server return a `CompletionList` object instead of just a list of `CompletionItem` objects, but that didn't help either.

**Comment by bubba** [comment]
This looks like an decoding issue with haskell-lsp, trying to decode that bit of JSON there gives:
```
*Language.Haskell.LSP.Test Data.Aeson BS> eitherDecode x :: Either String CompletionResponse
Left "Error in $.result[0]: When parsing the record CompletionItem of type Language.Haskell.LSP.Types.Completion.CompletionItem the key tags was not present."
```

**Comment by bubba** [comment]
Thanks for reporting this. Can you try out haskell-lsp master now and see if this fixes your crash? If that works then I can make a minor version release

**Comment by astoff** [comment]
I didn't want to look into how to build a Haskell library manually right now, but I can confirm that forcing every completion item to have a `tags` property makes the tests with the current Hackage version succeed again. So you must be on the right track here.

**Comment by bubba** [comment]
If you're using a cabal.project, try dropping this in

```
source-repository-package
    type: git
    location: https://github.com/alanz/haskell-lsp.git
    branch: master
    subdir: haskell-lsp-types
```

**Comment by kritzcreek** [comment]
Any chance for a bugfix release including the fix? I can work around it by pulling from git, but it would be nicer if I could just point at a hackage release.

**Comment by bubba** [comment]
@kritzcreek haskell-lsp-0.23.0.0 and haskell-lsp-types-0.23.0.0 are up on hackage now, and lsp-test should have a new revision bump for them too!

**Comment by kritzcreek** [comment]
Wow, what was quick! Thank you :)
